<?php

require_once '../Example.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-13 at 12:43:49.
 */
class ExampleTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Example
     */
    protected $object;

    /**
     *
     * @var Buzz\Browser 
     */
    protected $browser;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Example;
        $this->browser = new Buzz\Browser();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * Generated from @assert ("Voronezh") == expectedResult.
     *
     * @covers Example::getWeather
     */
    public function testGetWeather()
    {
        $expectedContent = $this->browser
                ->get('http://api.openweathermap.org/data/2.5/weather?q=Voronezh')
                ->getContent();
        $this->assertEquals(
                $expectedContent, Example::getWeather("Voronezh")
        );
    }

    /**
     * Generated from @assert ("Moscow") == expectedResult.
     *
     * @covers Example::getWeather
     */
    public function testGetWeather2()
    {
        $expectedContent = $this->browser
                ->get('http://api.openweathermap.org/data/2.5/weather?q=Moscow')
                ->getContent();
        $this->assertEquals(
                $expectedContent, Example::getWeather("Moscow")
        );
    }

    /**
     * Generated from @assert ("") == expectedResult.
     *
     * @covers Example::getWeather
     */
    public function testGetWeather3()
    {
        $expectedContent = $this->browser
                ->get('http://api.openweathermap.org/data/2.5/weather?q=')
                ->getContent();
        $this->assertEquals(
                $expectedContent, Example::getWeather("")
        );
    }

    /**
     * Generated from @assert (1) == expectedResult.
     *
     * @covers Example::getWeather
     */
    public function testGetWeather4()
    {
        $expectedContent = $this->browser
                ->get('http://api.openweathermap.org/data/2.5/weather?q=1')
                ->getContent();
        $this->assertEquals(
                $expectedContent, Example::getWeather(1)
        );
    }

    /**
     * @covers Example::trueMethod
     * @todo   Implement testTrueMethod().
     */
    public function testTrueMethod()
    {
        $this->assertTrue($this->object->trueMethod());
    }

    /**
     * @covers Example::otherMethod
     * @todo   Implement testFalseMethod().
     */
    public function testFalseMethod()
    {
        $this->assertTrue($this->object->falseMethod());
    }

}
