<?php
require_once '../Example.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-13 at 08:37:27.
 */
class ExampleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Example
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Example;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Example::someMethod
     * @todo   Implement testSomeMethod().
     */
    public function testSomeMethod() {
        $this->assertTrue($this->object->someMethod());
       
    }

    /**
     * @covers Example::otherMethod
     * @todo   Implement testOtherMethod().
     */
    public function testOtherMethod() {
        $this->assertTrue($this->object->otherMethod());
    }

}
